import http from "node:http";
import { brand } from "../../../packages/config/src/brand.ts";
import { calculateImpact } from "../../../packages/core/src/impact.ts";
import type { Interaction } from "../../../packages/core/src/interaction.ts";
import { MockPaymentProvider } from "../../../packages/payments/src/mock.ts";
import { EventStore } from "../../../packages/events/src/store.ts";
import { moderate } from "../../../packages/ai/src/moderation.ts";
import { StripePaymentProvider } from "../../../packages/payments/src/stripe.ts";
import { PostgresPaymentStore } from "../../../packages/database/src/payment-store.ts";

const provider = new MockPaymentProvider(); const store = new EventStore(); const creatorId = "demo-creator";
const durableStore = process.env.DATABASE_URL ? PostgresPaymentStore.fromEnvironment() : null;
if (durableStore) await durableStore.migrate();
const stripe = process.env.STRIPE_WEBHOOK_SECRET ? new StripePaymentProvider({ secretKey: process.env.STRIPE_SECRET_KEY || "", publishableKey: process.env.STRIPE_PUBLISHABLE_KEY || "", clientId: process.env.STRIPE_CONNECT_CLIENT_ID || "", webhookSecret: process.env.STRIPE_WEBHOOK_SECRET, origin: process.env.APP_ORIGIN || "http://localhost:3000" }) : null;
await provider.connectCreator(creatorId);
function page(body: string) { return `<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"/><title>${brand.productName}</title><style>body{margin:0;background:#f8f7ff;color:#17132b;font:16px system-ui}main{max-width:480px;margin:auto;padding:28px}h1{font-size:32px}input,textarea,button{box-sizing:border-box;width:100%;padding:14px;margin:8px 0;border-radius:12px;border:1px solid #ded9ef;font:inherit}button{background:${brand.colors.accent};color:white;border:0;font-weight:700}.card{background:white;border-radius:20px;padding:20px;box-shadow:0 8px 30px #36256d14}.small{color:#635d77;font-size:14px}</style></head><body><main>${body}</main></body></html>`; }
function json(res: http.ServerResponse, status: number, data: unknown) { res.writeHead(status, { "content-type":"application/json", "cache-control":"no-store" }); res.end(JSON.stringify(data)); }
async function body(req: http.IncomingMessage) { let s=""; for await (const c of req) s += c; return s; }
const server = http.createServer(async (req,res) => {
  const url = new URL(req.url || "/", "http://localhost");
  if (url.pathname === "/health") return json(res,200,{ok:true,provider:"mock",moneyCustody:false});
  if (url.pathname === `/support/${creatorId}` && req.method === "GET") return res.end(page(`<p class="small">Supporting</p><h1>✨ Creator Studio</h1><div class="card"><p>Make your message part of the live stream.</p><form id="f"><input name="name" placeholder="Your name" maxlength="40" required/><input name="amount" type="number" min="0.01" step="0.01" value="99" required/><textarea name="message" placeholder="Say something kind" maxlength="280" required></textarea><button>Send support</button></form><p class="small">Suggestions: ₹49 · ₹99 · ₹499 · ₹999</p><p id="result" class="small"></p></div><script>f.onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(f));let r=await fetch('/api/mock/support',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)});let x=await r.json();result.textContent=x.ok?'🔥 YOUR SUPPORT IS LIVE — it is queued for the overlay.':x.error}</script>`));
  if (url.pathname === `/overlay/${creatorId}`) return res.end(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;background:transparent;font-family:Inter,system-ui,sans-serif;color:#fff}#stage{height:100vh;display:grid;place-items:center;padding:42px;box-sizing:border-box}.beam{display:none;max-width:780px;width:100%;padding:5px;border-radius:28px;background:linear-gradient(120deg,#a78bfa,#f0abfc,#7dd3fc);box-shadow:0 24px 80px #120b32a8;animation:arrive .42s cubic-bezier(.2,.9,.2,1)}.inside{border-radius:24px;padding:26px 30px;background:linear-gradient(135deg,#171127f2,#29194af2);backdrop-filter:blur(12px)}.label{font-size:14px;letter-spacing:.14em;text-transform:uppercase;color:#ddd6fe}.who{font-size:24px;font-weight:800;margin-top:6px}.amount{font-size:48px;line-height:1;font-weight:850;letter-spacing:-.05em;margin:10px 0}.message{font-size:22px;line-height:1.35;margin:0;color:#f5f3ff;overflow-wrap:anywhere}@keyframes arrive{from{opacity:0;transform:translateY(24px) scale(.96)}to{opacity:1;transform:translateY(0) scale(1)}}@media(prefers-reduced-motion:reduce){.beam{animation:none}}</style></head><body><main id="stage"><section id="card" class="beam" aria-live="polite"><div class="inside"><div class="label">Live supporter</div><div id="who" class="who"></div><div id="amount" class="amount"></div><p id="message" class="message"></p></div></section></main><script>const seen=new Set(),e=new EventSource('/api/overlay/${creatorId}');e.onmessage=x=>{let i=JSON.parse(x.data);if(seen.has(i.id))return;seen.add(i.id);card.style.display='block';who.textContent='🔥 '+i.supporterName;amount.textContent=new Intl.NumberFormat('en-IN',{style:'currency',currency:i.currency}).format(i.amountMinor/100);message.textContent=i.message;setTimeout(()=>card.style.display='none',i.durationSeconds*1000)}</script></body></html>`);
  if (url.pathname === `/api/overlay/${creatorId}`) { res.writeHead(200,{"content-type":"text/event-stream","cache-control":"no-cache","connection":"keep-alive"}); const stop=store.subscribe(i=>res.write(`data: ${JSON.stringify({...i,durationSeconds:calculateImpact(i.amountMinor).durationSeconds})}\n\n`)); req.on("close",stop); return; }
  if (url.pathname === "/api/mock/support" && req.method === "POST") { try { const p=JSON.parse(await body(req)); const amountMinor=Math.round(Number(p.amount)*100); if (!Number.isInteger(amountMinor) || amountMinor < 1) throw new Error("Enter a valid amount."); if (!p.name || !p.message || p.message.length > 280) throw new Error("Please add a short name and message."); const impact=calculateImpact(amountMinor); const payment={creatorId,amountMinor,currency:"INR",supporterName:p.name,message:p.message,providerEventId:`mock_evt_${crypto.randomUUID()}`,paidAt:Date.now()}; const verified=await provider.handleWebhook(JSON.stringify(payment),{"x-mock-signature":"local-demo"}); if (!verified || !store.recordEvent(verified.providerEventId)) return json(res,202,{ok:true,duplicate:true}); const m=moderate(verified.message); if (!m.approved) return json(res,202,{ok:true,status:"acknowledged_not_displayed"}); const interaction: Interaction={id:crypto.randomUUID(),...verified,state:"QUEUED",receivedAt:Date.now(),impact:impact.priority}; store.add(interaction); return json(res,201,{ok:true,interactionId:interaction.id}); } catch(e) { return json(res,400,{ok:false,error:e instanceof Error?e.message:"Invalid request"}); } }
  if (url.pathname === "/api/webhooks/stripe" && req.method === "POST") { try { const raw=await body(req); if (!stripe) return json(res,503,{ok:false,error:"Stripe webhook secret is not configured"}); const verified=await stripe.handleWebhook(raw,{"stripe-signature":String(req.headers["stripe-signature"] || "")}); if (!verified) { console.log("stripe_webhook",{outcome:"ignored"}); return json(res,200,{ok:true,status:"ignored"}); } const m=moderate(verified.message); if (!m.approved) return json(res,200,{ok:true,status:"acknowledged_not_displayed"}); const interaction: Interaction={id:crypto.randomUUID(),...verified,state:"QUEUED",receivedAt:Date.now(),impact:calculateImpact(verified.amountMinor).priority}; if (durableStore) { const saved=await durableStore.recordVerifiedPayment(verified,interaction); if(!saved.created) return json(res,200,{ok:true,duplicate:true}); } else { if (!store.recordEvent(verified.providerEventId)) return json(res,200,{ok:true,duplicate:true}); store.add(interaction); } console.log("stripe_webhook",{outcome:"queued",eventId:verified.providerEventId}); return json(res,200,{ok:true,interactionId:interaction.id}); } catch { console.log("stripe_webhook",{outcome:"failed"}); return json(res,500,{ok:false,error:"Webhook processing failed"}); } }
  if (url.pathname === "/api/worker/drain" && req.method === "POST") { if (!durableStore) return json(res,503,{ok:false,error:"Durable store is unavailable"}); const count=await durableStore.drainOutbox(async interaction=>{store.add(interaction);}); return json(res,200,{ok:true,delivered:count}); }
  res.writeHead(404);res.end("Not found");
});
server.listen(3000,()=>console.log("Local demo: http://localhost:3000/support/demo-creator"));
