import http from "node:http";
import QRCode from "qrcode";
import { Pool } from "pg";
import { brand } from "../../../packages/config/src/brand.ts";
import { calculateImpact } from "../../../packages/core/src/impact.ts";
import type { Interaction } from "../../../packages/core/src/interaction.ts";
import { MockPaymentProvider } from "../../../packages/payments/src/mock.ts";
import { EventStore } from "../../../packages/events/src/store.ts";
import { moderate } from "../../../packages/ai/src/moderation.ts";
import { StripePaymentProvider } from "../../../packages/payments/src/stripe.ts";
import { PostgresPaymentStore } from "../../../packages/database/src/payment-store.ts";
import { PilotStore } from "../../../packages/database/src/pilot-store.ts";

const creatorId="demo-creator", provider=new MockPaymentProvider(), store=new EventStore();
const durableStore=process.env.DATABASE_URL?PostgresPaymentStore.fromEnvironment():null;
if(durableStore) await durableStore.migrate();
const pilot=process.env.DATABASE_URL?new PilotStore(new Pool({connectionString:process.env.DATABASE_URL})):null;
if(pilot) await pilot.ensureCreator(creatorId);
const stripe=process.env.STRIPE_WEBHOOK_SECRET?new StripePaymentProvider({secretKey:process.env.STRIPE_SECRET_KEY||"",publishableKey:process.env.STRIPE_PUBLISHABLE_KEY||"",clientId:process.env.STRIPE_CONNECT_CLIENT_ID||"",webhookSecret:process.env.STRIPE_WEBHOOK_SECRET,origin:process.env.APP_ORIGIN||"http://localhost:3000"}):null;
await provider.connectCreator(creatorId);
if(durableStore&&Number(process.env.AUTO_DRAIN_MS||0)>0) setInterval(()=>durableStore.drainOutbox(async interaction=>store.add(interaction)).catch(()=>console.warn("auto_drain_failed")),Number(process.env.AUTO_DRAIN_MS));
const adminToken=process.env.PILOT_ADMIN_TOKEN;
const esc=(x:string)=>x.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const page=(body:string)=>`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${brand.productName}</title><style>body{margin:0;background:#f8f7ff;color:#17132b;font:16px system-ui}main{max-width:640px;margin:auto;padding:22px}h1{font-size:30px}input,textarea,select,button{box-sizing:border-box;width:100%;padding:14px;margin:7px 0;border-radius:12px;border:1px solid #ded9ef;font:inherit}button{background:${brand.colors.accent};color:white;border:0;font-weight:700}.card{background:#fff;border-radius:20px;padding:20px;margin:12px 0;box-shadow:0 8px 30px #36256d14}.small{color:#635d77;font-size:14px}.ok{color:#176b44}.warn{color:#8c2c2c}a{color:${brand.colors.accent}}</style></head><body><main>${body}</main></body></html>`;
const json=(res:http.ServerResponse,status:number,data:unknown)=>{res.writeHead(status,{"content-type":"application/json","cache-control":"no-store"});res.end(JSON.stringify(data));};
async function body(req:http.IncomingMessage){let s="";for await(const c of req)s+=c;return s;}
function device(req:http.IncomingMessage){const ua=String(req.headers["user-agent"]||"");return /iPhone|Android/i.test(ua)?(/iPhone/i.test(ua)?"iphone":"android"):"desktop";}
function admin(req:http.IncomingMessage){return Boolean(adminToken&&req.headers["x-pilot-admin-token"]===adminToken);}
async function track(e:any){if(!pilot)return;try{await pilot.record(e);}catch(error){console.warn("pilot_tracking_failed",{eventType:e.eventType,code:(error as any)?.code});}}
async function creator(id:string){return pilot?await pilot.creator(id):id===creatorId?{id,name:"Creator Studio",cohort:"monetized",enabled:true}:null;}

const server=http.createServer(async(req,res)=>{const url=new URL(req.url||"/","http://localhost"); const parts=url.pathname.split("/").filter(Boolean);
  if(url.pathname==="/health") return json(res,200,{ok:true,provider:process.env.PAYMENT_PROVIDER||"mock",moneyCustody:false,pilot:!!pilot});
  if(parts[0]==="support"&&parts[1]&&req.method==="GET"){const c=await creator(parts[1]);if(!c||!c.enabled){res.writeHead(404);return res.end("Creator unavailable");} const streamId=url.searchParams.get("stream");await track({creatorId:c.id,streamId,eventType:"support_page_opened",deviceType:device(req)});return res.end(page(`<p class="small">Supporting ${esc(c.name)}</p><h1>✨ ${esc(c.name)}</h1><div class="card"><p>Make your message part of the live stream.</p><form id="f"><input name="name" placeholder="Your name" maxlength="40" required><input name="amount" type="number" min="0.01" step="0.01" value="99" required><textarea name="message" placeholder="Say something kind" maxlength="280" required></textarea><button>Continue to payment</button></form><p class="small">Suggested amounts: ₹49 · ₹99 · ₹499 · ₹999</p><p id="result" class="small"></p></div><script>let selected=performance.now();f.amount.onchange=()=>fetch('/api/pilot/event',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({creatorId:${JSON.stringify(c.id)},streamId:${JSON.stringify(streamId)},eventType:'amount_selected'})});f.onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(f));d.creatorId=${JSON.stringify(c.id)};d.streamId=${JSON.stringify(streamId)};d.startedAt=selected;let r=await fetch('/api/support',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)}),x=await r.json();if(x.checkoutUrl)location.assign(x.checkoutUrl);else result.textContent=x.ok?'Support queued.':x.error||'Unable to start payment'}</script>`));}
  if(parts[0]==="overlay"&&parts[1]) return res.end(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;background:transparent;font-family:system-ui;color:#fff}#stage{height:100vh;display:grid;place-items:center;padding:42px;box-sizing:border-box}.beam{display:none;max-width:780px;width:100%;padding:5px;border-radius:28px;background:linear-gradient(120deg,#a78bfa,#f0abfc,#7dd3fc);box-shadow:0 24px 80px #120b32a8}.inside{border-radius:24px;padding:26px 30px;background:#20143fee}.label{font-size:14px;letter-spacing:.14em;text-transform:uppercase;color:#ddd6fe}.who{font-size:24px;font-weight:800}.amount{font-size:48px;font-weight:850;margin:10px 0}.message{font-size:22px;overflow-wrap:anywhere}</style></head><body><main id="stage"><section id="card" class="beam"><div class="inside"><div class="label">Live supporter</div><div id="who" class="who"></div><div id="amount" class="amount"></div><div id="message" class="message"></div></div></section></main><script>const seen=new Set(),e=new EventSource('/api/overlay/${encodeURIComponent(parts[1])}');e.onmessage=async x=>{let i=JSON.parse(x.data);if(seen.has(i.id))return;seen.add(i.id);card.style.display='block';who.textContent='🔥 '+i.supporterName;amount.textContent=new Intl.NumberFormat('en-IN',{style:'currency',currency:i.currency}).format(i.amountMinor/100);message.textContent=i.message;fetch('/api/pilot/event',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({creatorId:i.creatorId,streamId:i.streamId,eventType:'interaction_displayed'})});setTimeout(()=>card.style.display='none',i.durationSeconds*1000)}</script></body></html>`);
  if(parts[0]==="api"&&parts[1]==="overlay"&&parts[2]){res.writeHead(200,{"content-type":"text/event-stream","cache-control":"no-cache","connection":"keep-alive"});const stop=store.subscribe(i=>{if(i.creatorId===parts[2])res.write(`data: ${JSON.stringify({...i,durationSeconds:calculateImpact(i.amountMinor).durationSeconds})}\n\n`)});req.on("close",stop);return;}
  if(url.pathname==="/api/pilot/event"&&req.method==="POST"){const e=JSON.parse(await body(req));await track({...e,deviceType:device(req)});return json(res,201,{ok:true});}
  if(url.pathname==="/api/pilot/test-alert"&&req.method==="POST"){const p=JSON.parse(await body(req)),c=await creator(p.creatorId);if(!c)return json(res,404,{ok:false});const interaction:Interaction={id:crypto.randomUUID(),creatorId:c.id,supporterName:"Test alert",message:"Beam is ready",amountMinor:1,currency:"INR",providerEventId:`test_${crypto.randomUUID()}`,receivedAt:Date.now(),state:"QUEUED",impact:20};store.add(interaction);return json(res,201,{ok:true});}
  if(url.pathname==="/api/support"&&req.method==="POST"){try{const p=JSON.parse(await body(req)),amountMinor=Math.round(Number(p.amount)*100),c=await creator(p.creatorId),started=Number(p.startedAt);if(!c||!Number.isInteger(amountMinor)||amountMinor<1||!p.name||!p.message)throw new Error("Enter a name, positive amount, and message.");const safety=pilot?await pilot.safety():{paymentsEnabled:true,interactionsEnabled:true};if(!safety.paymentsEnabled)return json(res,503,{ok:false,error:"Payments are temporarily paused."});await track({creatorId:c.id,streamId:p.streamId,eventType:"payment_started",deviceType:device(req),currency:"INR",amountMinor,checkoutDurationMs:Number.isFinite(started)?Math.round(performance.now()-started):undefined});if((process.env.PAYMENT_PROVIDER||"mock")==="stripe"){if(!stripe||!c.stripe_account_id)throw new Error("Creator payments are not connected.");stripe.setConnectedAccount(c.id,c.stripe_account_id);const payment=await stripe.createPayment({creatorId:c.id,streamId:p.streamId||undefined,amountMinor,currency:process.env.PILOT_CURRENCY||"INR",supporterName:p.name,message:p.message});return json(res,201,{ok:true,checkoutUrl:payment.checkoutUrl});}const interaction:Interaction={id:crypto.randomUUID(),creatorId:c.id,streamId:p.streamId||undefined,supporterName:p.name,message:p.message,amountMinor,currency:"INR",providerEventId:`mock_${crypto.randomUUID()}`,paidAt:Date.now(),receivedAt:Date.now(),state:"QUEUED",impact:calculateImpact(amountMinor).priority} as any;store.add(interaction);await track({creatorId:c.id,streamId:p.streamId,eventType:"payment_success",deviceType:device(req),currency:"INR",amountMinor,paymentMethodCategory:"mock"});return json(res,201,{ok:true,interactionId:interaction.id});}catch(e){return json(res,400,{ok:false,error:e instanceof Error?e.message:"Invalid request"});}}
  if(url.pathname==="/api/webhooks/stripe"&&req.method==="POST"){try{const raw=await body(req),verified=stripe&&await stripe.handleWebhook(raw,{"stripe-signature":String(req.headers["stripe-signature"]||"")});if(!verified)return json(res,200,{ok:true,status:"ignored"});const safety=pilot?await pilot.safety():{interactionsEnabled:true};const approved=moderate(verified.message).approved;const interaction=(safety.interactionsEnabled&&approved)?{id:crypto.randomUUID(),...verified,state:"QUEUED",receivedAt:Date.now(),impact:calculateImpact(verified.amountMinor).priority}:undefined;const saved=durableStore?await durableStore.recordVerifiedPayment(verified,interaction):{created:store.recordEvent(verified.providerEventId)};if(!saved.created)return json(res,200,{ok:true,duplicate:true});await track({creatorId:verified.creatorId,streamId:verified.streamId,eventType:"payment_success",currency:verified.currency,amountMinor:verified.amountMinor,paymentMethodCategory:"stripe"});if(interaction)await track({creatorId:verified.creatorId,streamId:verified.streamId,eventType:"interaction_queued",currency:verified.currency,amountMinor:verified.amountMinor});return json(res,200,{ok:true,recorded:true,interactionQueued:!!interaction});}catch{return json(res,500,{ok:false,error:"Webhook processing failed"});}}
  if(url.pathname==="/api/worker/drain"&&req.method==="POST"){if(!durableStore)return json(res,503,{ok:false});const count=await durableStore.drainOutbox(async i=>store.add(i));return json(res,200,{ok:true,delivered:count});}
  if(url.pathname==="/api/internal/deliver"&&req.method==="POST"){if(!process.env.OUTBOX_WORKER_TOKEN||req.headers["x-outbox-worker-token"]!==process.env.OUTBOX_WORKER_TOKEN)return json(res,401,{ok:false});const interaction=JSON.parse(await body(req)) as Interaction;store.add(interaction);return json(res,202,{ok:true});}
  if(url.pathname==="/pilot"&&req.method==="GET")return res.end(page(`<p class="small">Internal pilot control</p><h1>Beam pilot</h1><div class="card"><p>Use the creator link, QR code, OBS URL, and checklist for each stream.</p><p><a href="/pilot/${creatorId}">Open demo creator pilot mode</a></p></div>`));
  if(parts[0]==="pilot"&&parts[1]==="dashboard"&&parts[2]&&req.method==="GET")return res.end(page(`<p class="small">Internal pilot dashboard</p><h1>Stream metrics</h1><div class="card"><input id="token" type="password" placeholder="Pilot admin token"><button id="load">Load metrics</button><pre id="out" class="small"></pre></div><script>load.onclick=async()=>{let r=await fetch('/api/pilot/dashboard/${parts[2]}',{headers:{'x-pilot-admin-token':token.value}});out.textContent=JSON.stringify(await r.json(),null,2)}</script>`));
  if(parts[0]==="pilot"&&parts[1]&&parts[1]!=="setup"&&req.method==="GET"){const c=await creator(parts[1]);if(!c){res.writeHead(404);return res.end("Not found");}const origin=process.env.APP_ORIGIN||"http://localhost:3000",support=`${origin}/support/${c.id}`;const qr=await QRCode.toDataURL(support,{margin:1,width:220});return res.end(page(`<p class="small">Pilot mode · ${esc(c.cohort)}</p><h1>${esc(c.name)}</h1><div class="card"><b>Pre-stream checklist</b><p>□ YouTube ready<br>□ Payments connected<br>□ OBS connected<br>□ Support page working<br>□ Test alert displayed</p><b class="ok">READY TO STREAM</b></div><div class="card"><b>Supporter link</b><p><a href="${support}">${support}</a></p><img alt="Supporter QR code" src="${qr}"><p class="small">OBS: ${origin}/overlay/${c.id}</p><button onclick="fetch('/api/pilot/test-alert',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({creatorId:'${c.id}'})}).then(()=>alert('Test interaction sent'))">Send test interaction</button></div><div class="card"><b>Live health</b><p id="h">Checking…</p></div><script>fetch('/health').then(r=>r.json()).then(x=>h.textContent=x.ok?'Healthy · no custody':'Check service');</script>`));}
  if(parts[0]==="api"&&parts[1]==="pilot"&&parts[2]==="streams"&&req.method==="POST"){if(!admin(req))return json(res,401,{ok:false});const p=JSON.parse(await body(req));const id=await pilot?.createStream(p.creatorId,p.title||"Pilot stream");return json(res,201,{ok:true,id});}
  if(parts[0]==="api"&&parts[1]==="pilot"&&parts[2]==="creators"&&parts[3]&&parts[4]==="payment-account"&&req.method==="POST"){if(!admin(req)||!pilot)return json(res,401,{ok:false});const p=JSON.parse(await body(req)),accountId=String(p.stripeAccountId||"");if(!/^acct_[A-Za-z0-9]+$/.test(accountId))return json(res,400,{ok:false,error:"Enter a valid Stripe connected-account ID."});await pilot.setStripeAccount(parts[3],accountId);return json(res,200,{ok:true});}
  if(parts[0]==="api"&&parts[1]==="pilot"&&parts[2]==="dashboard"&&parts[3]&&req.method==="GET"){if(!admin(req))return json(res,401,{ok:false});return json(res,200,{ok:true,data:await pilot?.dashboard(parts[3])});}
  if(parts[0]==="api"&&parts[1]==="pilot"&&parts[2]==="safety"&&req.method==="POST"){if(!admin(req))return json(res,401,{ok:false});const p=JSON.parse(await body(req));await pilot?.setSafety({paymentsEnabled:!!p.paymentsEnabled,interactionsEnabled:!!p.interactionsEnabled});return json(res,200,{ok:true});}
  if(parts[0]==="pilot"&&parts[1]==="setup"&&parts[2]&&req.method==="GET")return res.end(page(`<p class="small">Internal setup</p><h1>Connect test payments</h1><div class="card"><p>Enter only the connected-account ID. Never enter a Stripe secret key here.</p><input id="token" type="password" placeholder="Pilot admin token"><input id="account" placeholder="acct_…"><button id="save">Save connected account</button><p id="result" class="small"></p></div><script>save.onclick=async()=>{let r=await fetch('/api/pilot/creators/${parts[2]}/payment-account',{method:'POST',headers:{'content-type':'application/json','x-pilot-admin-token':token.value},body:JSON.stringify({stripeAccountId:account.value})}),x=await r.json();result.textContent=x.ok?'Saved. You can now enable Stripe test mode in Render.':x.error||'Unable to save.'}</script>`));
  res.writeHead(404);res.end("Not found");
});
const port=Number(process.env.PORT||3000); server.listen(port,"0.0.0.0",()=>console.log(`Beam web listening on ${port}`));
