import http from "node:http";
import QRCode from "qrcode";
import { Pool } from "pg";
import { brand } from "../../../packages/config/src/brand.ts";
import { calculateImpact } from "../../../packages/core/src/impact.ts";
import type { Interaction } from "../../../packages/core/src/interaction.ts";
import { MockPaymentProvider } from "../../../packages/payments/src/mock.ts";
import { EventStore } from "../../../packages/events/src/store.ts";
import { moderate } from "../../../packages/ai/src/moderation.ts";
import { StripePaymentProvider } from "../../../packages/payments/src/stripe.ts";
import { PostgresPaymentStore } from "../../../packages/database/src/payment-store.ts";
import { PilotStore } from "../../../packages/database/src/pilot-store.ts";

const creatorId="demo-creator", provider=new MockPaymentProvider(), store=new EventStore();
const durableStore=process.env.DATABASE_URL?PostgresPaymentStore.fromEnvironment():null;
if(durableStore) await durableStore.migrate();
const pilot=process.env.DATABASE_URL?new PilotStore(new Pool({connectionString:process.env.DATABASE_URL})):null;
if(pilot) await pilot.ensureCreator(creatorId);
const stripe=process.env.STRIPE_WEBHOOK_SECRET?new StripePaymentProvider({secretKey:process.env.STRIPE_SECRET_KEY||"",publishableKey:process.env.STRIPE_PUBLISHABLE_KEY||"",clientId:process.env.STRIPE_CONNECT_CLIENT_ID||"",webhookSecret:process.env.STRIPE_WEBHOOK_SECRET,origin:process.env.APP_ORIGIN||"http://localhost:3000"}):null;
await provider.connectCreator(creatorId);
if(durableStore&&Number(process.env.AUTO_DRAIN_MS||0)>0) setInterval(()=>durableStore.drainOutbox(async interaction=>store.add(interaction)).catch(()=>console.warn("auto_drain_failed")),Number(process.env.AUTO_DRAIN_MS));
const adminToken=process.env.PILOT_ADMIN_TOKEN;
const youtubeReturnUrl=process.env.YOUTUBE_RETURN_URL||"https://www.youtube.com/";
const oauthStates=new Map<string,{kind:"youtube"|"stripe",creatorId?:string,createdAt:number}>();
const esc=(x:string)=>x.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const page=(body:string)=>`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${brand.productName}</title><style>body{margin:0;background:#f8f7ff;color:#17132b;font:16px system-ui}main{max-width:640px;margin:auto;padding:22px}h1{font-size:30px}input,textarea,select,button{box-sizing:border-box;width:100%;padding:14px;margin:7px 0;border-radius:12px;border:1px solid #ded9ef;font:inherit}button{background:${brand.colors.accent};color:white;border:0;font-weight:700}.card{background:#fff;border-radius:20px;padding:20px;margin:12px 0;box-shadow:0 8px 30px #36256d14}.small{color:#635d77;font-size:14px}.ok{color:#176b44}.warn{color:#8c2c2c}a{color:${brand.colors.accent}}</style></head><body><main>${body}</main></body></html>`;
const json=(res:http.ServerResponse,status:number,data:unknown)=>{res.writeHead(status,{"content-type":"application/json","cache-control":"no-store"});res.end(JSON.stringify(data));};
async function body(req:http.IncomingMessage){let s="";for await(const c of req)s+=c;return s;}
function device(req:http.IncomingMessage){const ua=String(req.headers["user-agent"]||"");return /iPhone|Android/i.test(ua)?(/iPhone/i.test(ua)?"iphone":"android"):"desktop";}
function admin(req:http.IncomingMessage){return Boolean(adminToken&&req.headers["x-pilot-admin-token"]===adminToken);}
function sessionToken(req:http.IncomingMessage){return String(req.headers.cookie||"").split(";").map(x=>x.trim()).find(x=>x.startsWith("beam_founder="))?.slice("beam_founder=".length)||"";}
function setSession(res:http.ServerResponse,token:string){res.setHeader("set-cookie",`beam_founder=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=43200`);}
async function signedInCreator(req:http.IncomingMessage){return pilot&&sessionToken(req)?pilot.sessionCreator(sessionToken(req)):null;}
const sandbox=`<p class="small warn"><b>Sandbox test mode</b> · No real money moves. Use Stripe test payment details only.</p>`;
async function track(e:any){if(!pilot)return;try{await pilot.record(e);}catch(error){console.warn("pilot_tracking_failed",{eventType:e.eventType,code:(error as any)?.code});}}
async function creator(id:string){return pilot?await pilot.creator(id):id===creatorId?{id,name:"Creator Studio",cohort:"monetized",enabled:true}:null;}
async function creatorDashboard(c:any){const origin=process.env.APP_ORIGIN||"http://localhost:3000",support=`${origin}/support/${c.id}`,qr=await QRCode.toDataURL(support,{margin:1,width:220});const recent=pilot?await pilot.recentInteractions(c.id):[];const youTube=c.youtube_connected_at?`<span class="ok">Connected ✓</span>`:`<a href="/auth/youtube/start">Connect YouTube</a>`;const payments=c.stripe_account_id?`<span class="ok">Connected ✓</span>`:`<a href="/auth/stripe/start">Connect Stripe sandbox</a>`;const obs=c.obs_confirmed_at?`<span class="ok">Connected ✓</span>`:`Setup required`;return page(`${sandbox}<p class="small">Creator dashboard</p><h1>Ready to go live</h1><div class="card"><p><b>YouTube</b> — ${youTube}</p><p><b>Payments</b> — ${payments}</p><p><b>Support page</b> — <span class="ok">Ready ✓</span></p><p><b>OBS</b> — ${obs}</p></div><div class="card"><b>Your supporter page</b><p><a href="${support}">${support}</a></p><img alt="QR code for your supporter page" src="${qr}"><p class="small">Fans scan this code or open the link.</p></div><div class="card"><b>Set up OBS</b><ol class="small"><li>In OBS, add a <b>Browser Source</b>.</li><li>Paste this address: <br><code>${origin}/overlay/${c.id}</code></li><li>Set size to 1280 × 720 and click OK.</li><li>Keep the source visible, then press Send test alert below.</li></ol><button id="test">Send test alert</button><p id="testResult" class="small"></p></div><div class="card"><b>Recent support</b>${recent.length?recent.map(x=>`<p><b>${esc(x.supporter_name)} · ${esc(x.currency)} ${(x.amount_minor/100).toFixed(2)}</b><br>${esc(x.message)}<br><span class="small">Payment received · ${new Date(x.received_at).toLocaleString()}</span></p>`).join(""):`<p class="small">No support yet. Your first completed sandbox payment will show here.</p>`}</div><script>document.querySelector('#test').onclick=async()=>{let test=document.querySelector('#test'),out=document.querySelector('#testResult');test.disabled=true;out.textContent='Sending…';let r=await fetch('/api/founder/test-alert',{method:'POST'}),x=await r.json();out.textContent=x.ok?'Test sent. Did it appear in OBS?':'Could not send the test alert. Refresh OBS, then try again.';if(x.ok){let b=document.createElement('button');b.textContent='I saw it';b.onclick=async()=>{await fetch('/api/founder/obs-confirm',{method:'POST'});location.reload()};out.appendChild(b)}}</script>`);}
async function inboxCard(c:any){const items=pilot?await pilot.recentInteractions(c.id):[];return `<div class="card"><b>Support Inbox</b><p class="small">Keep control of what you answer. Beam never promises a fan an answer.</p><p><a href="/creator/inbox">Open Support Inbox (${items.filter(x=>x.inbox_status==='NEW').length} new)</a></p></div>`;}

const server=http.createServer(async(req,res)=>{const url=new URL(req.url||"/","http://localhost"); const parts=url.pathname.split("/").filter(Boolean);
  if(url.pathname==="/health") return json(res,200,{ok:true,provider:process.env.PAYMENT_PROVIDER||"mock",moneyCustody:false,pilot:!!pilot,autoDrainMs:Number(process.env.AUTO_DRAIN_MS||0)});
  if(url.pathname==="/"&&req.method==="GET") return res.end(page(`${sandbox}<p class="small">Beam · live support for creators</p><h1>Let your live supporters be seen.</h1><div class="card"><p>Fans support you directly. Beam turns verified payments into live OBS interactions.</p><p><a href="/creator/start"><button>Start earning</button></a></p><p class="small">Already connected? <a href="/creator/dashboard">Open creator dashboard</a></p></div>`));
  if(url.pathname==="/creator/start"&&req.method==="GET"){const c=await signedInCreator(req);if(c){res.writeHead(302,{location:"/creator/dashboard"});return res.end();} if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)return res.end(page(`${sandbox}<h1>Creator setup is almost ready.</h1><div class="card"><p>Beam’s owner needs to enable the secure YouTube connection once. You will never need an API key or developer setup.</p><p class="small">After that, return here and choose Start earning.</p></div>`));res.writeHead(302,{location:"/auth/youtube/start"});return res.end();}
  if(url.pathname==="/creator/dashboard"&&req.method==="GET"){const c=await signedInCreator(req);if(!c){res.writeHead(302,{location:"/creator/start"});return res.end();}const html=await creatorDashboard(c);return res.end(html.replace("</main>",`${await inboxCard(c)}</main>`));}
  if(url.pathname==="/creator/inbox"&&req.method==="GET"){const c=await signedInCreator(req);if(!c){res.writeHead(302,{location:"/creator/start"});return res.end();}const items=pilot?await pilot.recentInteractions(c.id):[];const rows=items.length?items.map(x=>`<div class="card"><b>${esc(x.supporter_name)} · ${esc(x.currency)} ${(x.amount_minor/100).toFixed(2)}</b><p>${esc(x.message)}</p><p class="small">${esc(x.inbox_status)} · ${new Date(x.received_at).toLocaleString()}</p><select data-id="${x.id}" class="state"><option ${x.inbox_status==='NEW'?'selected':''}>NEW</option><option ${x.inbox_status==='SURFACED'?'selected':''}>SURFACED</option><option ${x.inbox_status==='ANSWERED'?'selected':''}>ANSWERED</option><option ${x.inbox_status==='ANSWER_LATER'?'selected':''}>ANSWER_LATER</option><option ${x.inbox_status==='SKIPPED'?'selected':''}>SKIPPED</option><option ${x.inbox_status==='MODERATED'?'selected':''}>MODERATED</option></select><button class="save" data-id="${x.id}">Save status</button>${x.moment_token?`<p><a href="/moment/${x.moment_token}">Open Your Moment</a></p>`:`<button class="moment" data-id="${x.id}">Create Your Moment</button>`}</div>`).join(""):`<div class="card"><p>No paid interactions yet.</p></div>`;return res.end(page(`${sandbox}<p><a href="/creator/dashboard">← Dashboard</a></p><h1>Support Inbox</h1><p class="small">Mark what you want to surface, answer later, skip, or moderate. Answered does not mean guaranteed.</p>${rows}<script>document.querySelectorAll('.save').forEach(b=>b.onclick=async()=>{let id=b.dataset.id,status=document.querySelector('.state[data-id="'+id+'"]').value;await fetch('/api/creator/inbox/'+id,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status})});location.reload()});document.querySelectorAll('.moment').forEach(b=>b.onclick=async()=>{let r=await fetch('/api/creator/inbox/'+b.dataset.id+'/moment',{method:'POST'}),x=await r.json();if(x.url)location.assign(x.url)})}</script>`));}
  if(parts[0]==="moment"&&parts[1]&&req.method==="GET"){const m=await pilot?.moment(parts[1]);if(!m){res.writeHead(404);return res.end("Moment unavailable");}return res.end(page(`<p class="small">Your Moment · Beam sandbox</p><h1>${esc(m.creator_name)} heard you.</h1><div class="card"><p class="small">Your question</p><p><b>${esc(m.message)}</b></p><p class="small">Asked by ${esc(m.supporter_name)} · ${esc(m.currency)} ${(m.amount_minor/100).toFixed(2)}</p><p>This is a shareable record of a creator-marked moment. It is not a video clip or a promise of future access.</p></div>`));}
  if(parts[0]==="api"&&parts[1]==="creator"&&parts[2]==="inbox"&&parts[3]&&!parts[4]&&req.method==="POST"){const c=await signedInCreator(req);const p=JSON.parse(await body(req));const allowed=["NEW","SURFACED","ANSWERED","ANSWER_LATER","SKIPPED","MODERATED"];if(!c||!allowed.includes(p.status))return json(res,400,{ok:false});return json(res,200,{ok:await pilot?.setInboxStatus(c.id,parts[3],p.status)});}
  if(parts[0]==="api"&&parts[1]==="creator"&&parts[2]==="inbox"&&parts[3]&&parts[4]==="moment"&&req.method==="POST"){const c=await signedInCreator(req);if(!c)return json(res,401,{ok:false});await pilot?.setInboxStatus(c.id,parts[3],"ANSWERED");const token=await pilot?.createMoment(c.id,parts[3]);return token?json(res,201,{ok:true,url:`/moment/${token}`}):json(res,404,{ok:false});}
  if(url.pathname==="/auth/youtube/start"&&req.method==="GET"){if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)return res.end(page(`${sandbox}<h1>YouTube connection is not enabled yet.</h1><p>Return to Beam after the owner enables it.</p>`));const state=crypto.randomUUID();oauthStates.set(state,{kind:"youtube",createdAt:Date.now()});const redirect=process.env.GOOGLE_REDIRECT_URI||`${process.env.APP_ORIGIN||"http://localhost:3000"}/auth/youtube/callback`;const q=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:redirect,response_type:"code",scope:"openid email https://www.googleapis.com/auth/youtube.readonly",state,access_type:"offline",prompt:"consent"});res.writeHead(302,{location:`https://accounts.google.com/o/oauth2/v2/auth?${q}`});return res.end();}
  if(url.pathname==="/auth/youtube/callback"&&req.method==="GET"){const state=url.searchParams.get("state")||"",code=url.searchParams.get("code")||"",pending=oauthStates.get(state);oauthStates.delete(state);if(!pending||pending.kind!=="youtube"||!code)return res.end(page(`${sandbox}<h1>We could not connect YouTube.</h1><p>For your protection, please return to Beam and try again.</p>`));try{const redirect=process.env.GOOGLE_REDIRECT_URI||`${process.env.APP_ORIGIN||"http://localhost:3000"}/auth/youtube/callback`;const token=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID||"",client_secret:process.env.GOOGLE_CLIENT_SECRET||"",redirect_uri:redirect,grant_type:"authorization_code"})}).then(async r=>r.ok?r.json():Promise.reject(new Error("Google sign-in was not accepted")));const channels=await fetch("https://www.googleapis.com/youtube/v3/channels?part=snippet&mine=true",{headers:{authorization:`Bearer ${token.access_token}`}}).then(async r=>r.ok?r.json():Promise.reject(new Error("Beam could not find a YouTube channel on this account.")));const channel=channels.items?.[0];if(!channel)throw new Error("No YouTube channel was found. Create or select a channel, then try again.");const id=`youtube-${channel.id}`;await pilot?.ensureCreator(id,channel.snippet?.title||"YouTube creator");await pilot?.connectYouTube(id,channel.id,channel.snippet?.title||"YouTube creator");const session=await pilot?.createSession(id);if(!session)throw new Error("Creator setup needs the secure database connection.");setSession(res,session);res.writeHead(302,{location:"/creator/dashboard"});return res.end();}catch(e){return res.end(page(`${sandbox}<h1>We could not connect YouTube.</h1><div class="card"><p>${esc(e instanceof Error?e.message:"Please try again.")}</p><p><a href="/creator/start">Return to Beam</a></p></div>`));}}
  if(url.pathname==="/auth/stripe/start"&&req.method==="GET"){const c=await signedInCreator(req);if(!c){res.writeHead(302,{location:"/creator/start"});return res.end();}if(!stripe||!process.env.STRIPE_CONNECT_CLIENT_ID)return res.end(page(`${sandbox}<h1>Payments setup is not enabled yet.</h1><p>Beam’s owner must enable the secure Stripe connection first. You never enter a Beam API key.</p>`));const state=await stripe.connectCreator(c.id);oauthStates.set(state,{kind:"stripe",creatorId:c.id,createdAt:Date.now()});res.writeHead(302,{location:stripe.onboardingUrl(state)});return res.end();}
  if(url.pathname==="/auth/stripe/callback"&&req.method==="GET"){const state=url.searchParams.get("state")||"",code=url.searchParams.get("code")||"",pending=oauthStates.get(state);oauthStates.delete(state);if(!pending||pending.kind!=="stripe"||!code)return res.end(page(`${sandbox}<h1>We could not connect Stripe.</h1><p>Return to your dashboard and try again.</p>`));try{const id=await stripe?.completeOnboarding(code,state);if(!id)throw new Error("Stripe did not return an account.");await pilot?.setStripeAccount(pending.creatorId!,id);res.writeHead(302,{location:"/creator/dashboard"});return res.end();}catch{return res.end(page(`${sandbox}<h1>We could not connect Stripe.</h1><p><a href="/creator/dashboard">Return to your dashboard</a></p>`));}}
  if(url.pathname==="/api/founder/test-alert"&&req.method==="POST"){const c=await signedInCreator(req);if(!c)return json(res,401,{ok:false});const interaction:Interaction={id:crypto.randomUUID(),creatorId:c.id,supporterName:"Test alert",message:"Your Beam overlay is ready",amountMinor:1,currency:process.env.PILOT_CURRENCY||"INR",providerEventId:`test_${crypto.randomUUID()}`,receivedAt:Date.now(),state:"QUEUED",impact:20};store.add(interaction);return json(res,201,{ok:true});}
  if(url.pathname==="/api/founder/obs-confirm"&&req.method==="POST"){const c=await signedInCreator(req);if(!c)return json(res,401,{ok:false});await pilot?.confirmObs(c.id);return json(res,200,{ok:true});}
  if(url.pathname==="/support/success"&&req.method==="GET"){const id=url.searchParams.get("creator_id")||creatorId,streamId=url.searchParams.get("stream_id");return res.end(page(`<p class="small ok">Payment received</p><h1>Thank you for supporting the stream.</h1><div class="card"><p>Your payment is confirmed by the payment provider. Your message will appear when it is processed.</p><button id="back">Return to YouTube</button></div><script>back.onclick=async()=>{await fetch('/api/pilot/event',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({creatorId:${JSON.stringify(id)},streamId:${JSON.stringify(streamId)},eventType:'return_to_youtube'})});location.assign(${JSON.stringify(youtubeReturnUrl)})}</script>`));}
  if(url.pathname==="/support/cancel"&&req.method==="GET"){const id=url.searchParams.get("creator_id")||creatorId,streamId=url.searchParams.get("stream_id");await track({creatorId:id,streamId,eventType:"payment_failed",failureReason:"checkout_cancelled"});return res.end(page(`<p class="small">Payment cancelled</p><h1>No payment was made.</h1><div class="card"><p>You can return to the stream or try again when ready.</p><p><a href="/support/${encodeURIComponent(id)}">Try again</a></p></div>`));}
  if(parts[0]==="support"&&parts[1]&&req.method==="GET"){const c=await creator(parts[1]);if(!c||!c.enabled){res.writeHead(404);return res.end("Creator unavailable");} const streamId=url.searchParams.get("stream"),currency=(process.env.PILOT_CURRENCY||"INR").toUpperCase(),suggestions=currency==="INR"?"₹49 · ₹99 · ₹499 · ₹999":`${currency} 5 · ${currency} 10 · ${currency} 25 · ${currency} 50`;await track({creatorId:c.id,streamId,eventType:"support_page_opened",deviceType:device(req)});return res.end(page(`${sandbox}<p class="small">Supporting ${esc(c.name)}</p><h1>✨ ${esc(c.name)}</h1><div class="card"><p>Make your message part of the live stream.</p><form id="f"><input name="name" placeholder="Your name" maxlength="40" required><input name="amount" type="number" min="0.01" step="0.01" value="5" required><textarea name="message" placeholder="Say something kind" maxlength="280" required></textarea><button>Continue to secure payment</button></form><p class="small">Enter any positive amount. Suggestions: ${suggestions}</p><p id="result" class="small"></p></div><script>let selected=performance.now();f.amount.onchange=()=>fetch('/api/pilot/event',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({creatorId:${JSON.stringify(c.id)},streamId:${JSON.stringify(streamId)},eventType:'amount_selected'})});f.onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(f));d.creatorId=${JSON.stringify(c.id)};d.streamId=${JSON.stringify(streamId)};let r=await fetch('/api/support',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)}),x=await r.json();if(x.checkoutUrl)location.assign(x.checkoutUrl);else result.textContent=x.ok?'Support received.':x.error||'Unable to start payment'}</script>`));}
  if(parts[0]==="overlay"&&parts[1]) return res.end(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;background:transparent;font-family:system-ui;color:#fff}#stage{height:100vh;display:grid;place-items:center;padding:42px;box-sizing:border-box}.beam{display:none;max-width:780px;width:100%;padding:5px;border-radius:28px;background:linear-gradient(120deg,#a78bfa,#f0abfc,#7dd3fc);box-shadow:0 24px 80px #120b32a8}.inside{border-radius:24px;padding:26px 30px;background:#20143fee}.label{font-size:14px;letter-spacing:.14em;text-transform:uppercase;color:#ddd6fe}.who{font-size:24px;font-weight:800}.amount{font-size:48px;font-weight:850;margin:10px 0}.message{font-size:22px;overflow-wrap:anywhere}</style></head><body><main id="stage"><section id="card" class="beam"><div class="inside"><div class="label">Live supporter</div><div id="who" class="who"></div><div id="amount" class="amount"></div><div id="message" class="message"></div></div></section></main><script>const seen=new Set(),e=new EventSource('/api/overlay/${encodeURIComponent(parts[1])}');e.onmessage=async x=>{let i=JSON.parse(x.data);if(seen.has(i.id))return;seen.add(i.id);card.style.display='block';who.textContent='🔥 '+i.supporterName;amount.textContent=new Intl.NumberFormat('en-IN',{style:'currency',currency:i.currency}).format(i.amountMinor/100);message.textContent=i.message;fetch('/api/pilot/event',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({creatorId:i.creatorId,streamId:i.streamId,eventType:'interaction_displayed'})});setTimeout(()=>card.style.display='none',i.durationSeconds*1000)}</script></body></html>`);
  if(parts[0]==="api"&&parts[1]==="overlay"&&parts[2]){res.writeHead(200,{"content-type":"text/event-stream","cache-control":"no-cache","connection":"keep-alive"});const stop=store.subscribe(i=>{if(i.creatorId===parts[2])res.write(`data: ${JSON.stringify({...i,durationSeconds:calculateImpact(i.amountMinor).durationSeconds})}\n\n`)});req.on("close",stop);return;}
  if(url.pathname==="/api/pilot/event"&&req.method==="POST"){const e=JSON.parse(await body(req));await track({...e,deviceType:device(req)});return json(res,201,{ok:true});}
  if(url.pathname==="/api/pilot/test-alert"&&req.method==="POST"){const p=JSON.parse(await body(req)),c=await creator(p.creatorId);if(!c)return json(res,404,{ok:false});const interaction:Interaction={id:crypto.randomUUID(),creatorId:c.id,supporterName:"Test alert",message:"Beam is ready",amountMinor:1,currency:"INR",providerEventId:`test_${crypto.randomUUID()}`,receivedAt:Date.now(),state:"QUEUED",impact:20};store.add(interaction);return json(res,201,{ok:true});}
  if(url.pathname==="/api/support"&&req.method==="POST"){try{const p=JSON.parse(await body(req)),amountMinor=Math.round(Number(p.amount)*100),c=await creator(p.creatorId),started=Number(p.startedAt);if(!c||!Number.isInteger(amountMinor)||amountMinor<1||!p.name||!p.message)throw new Error("Enter a name, positive amount, and message.");const safety=pilot?await pilot.safety():{paymentsEnabled:true,interactionsEnabled:true};if(!safety.paymentsEnabled)return json(res,503,{ok:false,error:"Payments are temporarily paused."});await track({creatorId:c.id,streamId:p.streamId,eventType:"payment_started",deviceType:device(req),currency:"INR",amountMinor,checkoutDurationMs:Number.isFinite(started)?Math.round(performance.now()-started):undefined});if((process.env.PAYMENT_PROVIDER||"mock")==="stripe"){if(!stripe||!c.stripe_account_id)throw new Error("Creator payments are not connected.");stripe.setConnectedAccount(c.id,c.stripe_account_id);const payment=await stripe.createPayment({creatorId:c.id,streamId:p.streamId||undefined,amountMinor,currency:process.env.PILOT_CURRENCY||"INR",supporterName:p.name,message:p.message});return json(res,201,{ok:true,checkoutUrl:payment.checkoutUrl});}const interaction:Interaction={id:crypto.randomUUID(),creatorId:c.id,streamId:p.streamId||undefined,supporterName:p.name,message:p.message,amountMinor,currency:"INR",providerEventId:`mock_${crypto.randomUUID()}`,paidAt:Date.now(),receivedAt:Date.now(),state:"QUEUED",impact:calculateImpact(amountMinor).priority} as any;store.add(interaction);await track({creatorId:c.id,streamId:p.streamId,eventType:"payment_success",deviceType:device(req),currency:"INR",amountMinor,paymentMethodCategory:"mock"});return json(res,201,{ok:true,interactionId:interaction.id});}catch(e){return json(res,400,{ok:false,error:e instanceof Error?e.message:"Invalid request"});}}
  if(url.pathname==="/api/webhooks/stripe"&&req.method==="POST"){try{const raw=await body(req),verified=stripe&&await stripe.handleWebhook(raw,{"stripe-signature":String(req.headers["stripe-signature"]||"")});if(!verified)return json(res,200,{ok:true,status:"ignored"});const safety=pilot?await pilot.safety():{interactionsEnabled:true};const approved=moderate(verified.message).approved;const interaction=(safety.interactionsEnabled&&approved)?{id:crypto.randomUUID(),...verified,state:"QUEUED",receivedAt:Date.now(),impact:calculateImpact(verified.amountMinor).priority}:undefined;const saved=durableStore?await durableStore.recordVerifiedPayment(verified,interaction):{created:store.recordEvent(verified.providerEventId)};if(!saved.created)return json(res,200,{ok:true,duplicate:true});await track({creatorId:verified.creatorId,streamId:verified.streamId,eventType:"payment_success",currency:verified.currency,amountMinor:verified.amountMinor,paymentMethodCategory:"stripe"});if(interaction)await track({creatorId:verified.creatorId,streamId:verified.streamId,eventType:"interaction_queued",currency:verified.currency,amountMinor:verified.amountMinor});return json(res,200,{ok:true,recorded:true,interactionQueued:!!interaction});}catch{return json(res,500,{ok:false,error:"Webhook processing failed"});}}
  if(url.pathname==="/api/worker/drain"&&req.method==="POST"){if(process.env.NODE_ENV==="production")return json(res,404,{ok:false});if(!durableStore)return json(res,503,{ok:false});const count=await durableStore.drainOutbox(async i=>store.add(i));return json(res,200,{ok:true,delivered:count});}
  if(url.pathname==="/api/internal/deliver"&&req.method==="POST"){if(!process.env.OUTBOX_WORKER_TOKEN||req.headers["x-outbox-worker-token"]!==process.env.OUTBOX_WORKER_TOKEN)return json(res,401,{ok:false});const interaction=JSON.parse(await body(req)) as Interaction;store.add(interaction);return json(res,202,{ok:true});}
  if(url.pathname==="/pilot"&&req.method==="GET")return res.end(page(`<p class="small">Internal pilot control</p><h1>Beam pilot</h1><div class="card"><p>Use the creator link, QR code, OBS URL, and checklist for each stream.</p><p><a href="/pilot/${creatorId}">Open demo creator pilot mode</a></p></div>`));
  if(parts[0]==="pilot"&&parts[1]==="dashboard"&&parts[2]&&req.method==="GET")return res.end(page(`<p class="small">Internal pilot dashboard</p><h1>Stream metrics</h1><div class="card"><input id="token" type="password" placeholder="Pilot admin token"><button id="load">Load metrics</button><pre id="out" class="small"></pre></div><script>load.onclick=async()=>{let r=await fetch('/api/pilot/dashboard/${parts[2]}',{headers:{'x-pilot-admin-token':token.value}});out.textContent=JSON.stringify(await r.json(),null,2)}</script>`));
  if(parts[0]==="pilot"&&parts[1]&&parts[1]!=="setup"&&req.method==="GET"){const c=await creator(parts[1]);if(!c){res.writeHead(404);return res.end("Not found");}const origin=process.env.APP_ORIGIN||"http://localhost:3000",support=`${origin}/support/${c.id}`;const qr=await QRCode.toDataURL(support,{margin:1,width:220});return res.end(page(`<p class="small">Pilot mode · ${esc(c.cohort)}</p><h1>${esc(c.name)}</h1><div class="card"><b>Pre-stream checklist</b><p>□ YouTube ready<br>□ Payments connected<br>□ OBS connected<br>□ Support page working<br>□ Test alert displayed</p><b class="ok">READY TO STREAM</b></div><div class="card"><b>Supporter link</b><p><a href="${support}">${support}</a></p><img alt="Supporter QR code" src="${qr}"><p class="small">OBS: ${origin}/overlay/${c.id}</p><button onclick="fetch('/api/pilot/test-alert',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({creatorId:'${c.id}'})}).then(()=>alert('Test interaction sent'))">Send test interaction</button></div><div class="card"><b>Live health</b><p id="h">Checking…</p></div><script>fetch('/health').then(r=>r.json()).then(x=>h.textContent=x.ok?'Healthy · no custody':'Check service');</script>`));}
  if(parts[0]==="api"&&parts[1]==="pilot"&&parts[2]==="streams"&&req.method==="POST"){if(!admin(req))return json(res,401,{ok:false});const p=JSON.parse(await body(req));const id=await pilot?.createStream(p.creatorId,p.title||"Pilot stream");return json(res,201,{ok:true,id});}
  if(parts[0]==="api"&&parts[1]==="pilot"&&parts[2]==="creators"&&parts[3]&&parts[4]==="payment-account"&&req.method==="POST"){if(!admin(req)||!pilot)return json(res,401,{ok:false});const p=JSON.parse(await body(req)),accountId=String(p.stripeAccountId||"");if(!/^acct_[A-Za-z0-9]+$/.test(accountId))return json(res,400,{ok:false,error:"Enter a valid Stripe connected-account ID."});await pilot.setStripeAccount(parts[3],accountId);return json(res,200,{ok:true});}
  if(parts[0]==="api"&&parts[1]==="pilot"&&parts[2]==="dashboard"&&parts[3]&&req.method==="GET"){if(!admin(req))return json(res,401,{ok:false});return json(res,200,{ok:true,data:await pilot?.dashboard(parts[3])});}
  if(parts[0]==="api"&&parts[1]==="pilot"&&parts[2]==="safety"&&req.method==="POST"){if(!admin(req))return json(res,401,{ok:false});const p=JSON.parse(await body(req));await pilot?.setSafety({paymentsEnabled:!!p.paymentsEnabled,interactionsEnabled:!!p.interactionsEnabled});return json(res,200,{ok:true});}
  if(parts[0]==="pilot"&&parts[1]==="setup"&&parts[2]&&req.method==="GET")return res.end(page(`<p class="small">Internal setup</p><h1>Connect test payments</h1><div class="card"><p>Enter only the connected-account ID. Never enter a Stripe secret key here.</p><input id="token" type="password" placeholder="Pilot admin token"><input id="account" placeholder="acct_…"><button id="save">Save connected account</button><p id="result" class="small"></p></div><script>save.onclick=async()=>{let r=await fetch('/api/pilot/creators/${parts[2]}/payment-account',{method:'POST',headers:{'content-type':'application/json','x-pilot-admin-token':token.value},body:JSON.stringify({stripeAccountId:account.value})}),x=await r.json();result.textContent=x.ok?'Saved. You can now enable Stripe test mode in Render.':x.error||'Unable to save.'}</script>`));
  res.writeHead(404);res.end("Not found");
});
const port=Number(process.env.PORT||3000); server.listen(port,"0.0.0.0",()=>console.log(`Beam web listening on ${port}`));
