import { createHash, randomUUID } from "node:crypto";
import { Pool } from "pg";

export type Cohort = "monetized" | "non_monetized";
export type PilotEvent = { creatorId:string; streamId?:string|null; eventType:string; deviceType?:string; country?:string; currency?:string; amountMinor?:number; paymentMethodCategory?:string; checkoutDurationMs?:number; failureReason?:string; metadata?:Record<string,unknown> };
export class PilotStore {
  private pool: Pool;
  constructor(pool: Pool) { this.pool=pool; }
  async ensureCreator(id:string,name:string="Creator Studio",cohort:Cohort="monetized") { await this.pool.query("INSERT INTO pilot_creators (id,name,cohort) VALUES ($1,$2,$3) ON CONFLICT (id) DO NOTHING",[id,name,cohort]); }
  async creator(id:string) { return (await this.pool.query("SELECT * FROM pilot_creators WHERE id=$1",[id])).rows[0] as any; }
  async setStripeAccount(id:string,accountId:string) { await this.pool.query("UPDATE pilot_creators SET stripe_account_id=$2 WHERE id=$1",[id,accountId]); }
  async connectYouTube(id:string,channelId:string,name:string) { await this.pool.query("UPDATE pilot_creators SET youtube_channel_id=$2,youtube_connected_at=now(),name=$3 WHERE id=$1",[id,channelId,name]); }
  async confirmObs(id:string) { await this.pool.query("UPDATE pilot_creators SET obs_confirmed_at=now() WHERE id=$1",[id]); }
  private hash(token:string) { return createHash("sha256").update(token).digest("hex"); }
  async createSession(creatorId:string) { const token=randomUUID()+randomUUID(); await this.pool.query("DELETE FROM founder_sessions WHERE expires_at < now()"); await this.pool.query("INSERT INTO founder_sessions (token_hash,creator_id,expires_at) VALUES ($1,$2,now()+interval '12 hours')",[this.hash(token),creatorId]); return token; }
  async sessionCreator(token:string) { return (await this.pool.query("SELECT c.* FROM founder_sessions s JOIN pilot_creators c ON c.id=s.creator_id WHERE s.token_hash=$1 AND s.expires_at>now()",[this.hash(token)])).rows[0] as any; }
  async createOAuthState(kind:"youtube"|"stripe",creatorId?:string) { const state=randomUUID()+randomUUID(); await this.pool.query("DELETE FROM founder_oauth_states WHERE expires_at < now()"); await this.pool.query("INSERT INTO founder_oauth_states (state,kind,creator_id,expires_at) VALUES ($1,$2,$3,now()+interval '15 minutes')",[state,kind,creatorId||null]); return state; }
  async consumeOAuthState(state:string,kind:"youtube"|"stripe") { return (await this.pool.query("DELETE FROM founder_oauth_states WHERE state=$1 AND kind=$2 AND expires_at>now() RETURNING creator_id",[state,kind])).rows[0] as any; }
  async recentInteractions(creatorId:string) { return (await this.pool.query("SELECT i.id,i.supporter_name,i.message,i.amount_minor,i.currency,i.state,i.received_at,coalesce(s.status,'NEW') inbox_status,m.token moment_token FROM interactions i LEFT JOIN support_inbox s ON s.interaction_id=i.id LEFT JOIN supporter_moments m ON m.interaction_id=i.id WHERE i.creator_id=$1 ORDER BY i.received_at DESC LIMIT 20",[creatorId])).rows as any[]; }
  async setInboxStatus(creatorId:string,interactionId:string,status:"NEW"|"SURFACED"|"ANSWERED"|"ANSWER_LATER"|"SKIPPED"|"MODERATED") { const r=await this.pool.query("SELECT 1 FROM interactions WHERE id=$1 AND creator_id=$2",[interactionId,creatorId]); if(!r.rowCount) return false; await this.pool.query("INSERT INTO support_inbox (interaction_id,creator_id,status) VALUES ($1,$2,$3) ON CONFLICT (interaction_id) DO UPDATE SET status=$3,updated_at=now()",[interactionId,creatorId,status]); return true; }
  async createMoment(creatorId:string,interactionId:string,answerTimestampSeconds?:number) { const r=await this.pool.query("SELECT 1 FROM interactions WHERE id=$1 AND creator_id=$2",[interactionId,creatorId]); if(!r.rowCount) return null; const token=randomUUID(); const result=await this.pool.query("INSERT INTO supporter_moments (interaction_id,creator_id,token,answer_timestamp_seconds) VALUES ($1,$2,$3,$4) ON CONFLICT (interaction_id) DO UPDATE SET answer_timestamp_seconds=coalesce(EXCLUDED.answer_timestamp_seconds,supporter_moments.answer_timestamp_seconds) RETURNING token",[interactionId,creatorId,token,Number.isInteger(answerTimestampSeconds)?answerTimestampSeconds:null]); return result.rows[0].token as string; }
  async moment(token:string) { return (await this.pool.query("SELECT m.answer_timestamp_seconds,i.supporter_name,i.message,i.amount_minor,i.currency,c.name creator_name,c.youtube_channel_id FROM supporter_moments m JOIN interactions i ON i.id=m.interaction_id JOIN pilot_creators c ON c.id=m.creator_id WHERE m.token=$1",[token])).rows[0] as any; }
  async founderMetrics(creatorId:string) { const r=await this.pool.query(`SELECT event_type,occurred_at,checkout_duration_ms FROM pilot_events WHERE creator_id=$1 ORDER BY occurred_at`,[creatorId]); const events=r.rows; const first=events.find(x=>x.event_type==='creator_onboarding_started')?.occurred_at; const ready=events.find(x=>x.event_type==='creator_ready')?.occurred_at; const starts=events.filter(x=>x.event_type==='payment_started'), paid=events.filter(x=>x.event_type==='payment_success'); return {creatorOnboardingMs:first&&ready?new Date(ready).getTime()-new Date(first).getTime():null,creatorActions:events.filter(x=>x.event_type.startsWith('creator_')).length,fanActions:starts.length+paid.length,fanCheckoutMs:starts.at(-1)?.checkout_duration_ms||null,payments:paid.length}; }
  async record(e:PilotEvent) { await this.pool.query("INSERT INTO pilot_events (id,creator_id,stream_id,event_type,device_type,country,currency,amount_minor,payment_method_category,checkout_duration_ms,failure_reason,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)",[randomUUID(),e.creatorId,e.streamId||null,e.eventType,e.deviceType||null,e.country||null,e.currency||null,e.amountMinor||null,e.paymentMethodCategory||null,e.checkoutDurationMs||null,e.failureReason||null,e.metadata||{}]); }
  async safety() { return (await this.pool.query("SELECT value FROM pilot_settings WHERE key='safety'" )).rows[0]?.value || {paymentsEnabled:true,interactionsEnabled:true}; }
  async setSafety(value:{paymentsEnabled:boolean;interactionsEnabled:boolean}) { await this.pool.query("INSERT INTO pilot_settings (key,value,updated_at) VALUES ('safety',$1,now()) ON CONFLICT (key) DO UPDATE SET value=$1,updated_at=now()",[value]); }
  async createStream(creatorId:string,title:string) { const id=randomUUID(); await this.pool.query("INSERT INTO pilot_streams (id,creator_id,title) VALUES ($1,$2,$3)",[id,creatorId,title]); return id; }
  async stream(id:string) { return (await this.pool.query("SELECT * FROM pilot_streams WHERE id=$1",[id])).rows[0] as any; }
  async setStream(id:string,status:string,nativeCount:number,nativeAmountMinor:number,nativeCurrency?:string) { await this.pool.query("UPDATE pilot_streams SET status=$2,native_superchat_count=$3,native_superchat_amount_minor=$4,native_superchat_currency=$5,ended_at=CASE WHEN $2='ended' THEN now() ELSE ended_at END WHERE id=$1",[id,status,nativeCount,nativeAmountMinor,nativeCurrency||null]); }
  async dashboard(streamId:string) { const s=await this.stream(streamId); if(!s) return null; const r=await this.pool.query(`SELECT event_type,count(*)::int count,coalesce(sum(amount_minor),0)::int amount,coalesce(avg(checkout_duration_ms),0)::int avg_ms FROM pilot_events WHERE stream_id=$1 GROUP BY event_type`,[streamId]); const m=Object.fromEntries(r.rows.map(x=>[x.event_type,x])); const successes=m.payment_success?.count||0, starts=m.payment_started?.count||0, displayed=m.interaction_displayed?.count||0, beamAmount=m.payment_success?.amount||0, nativeCount=s.native_superchat_count||0, nativeAmount=s.native_superchat_amount_minor||0; return {stream:s,events:m,beam:{payers:successes,gmv:beamAmount,averagePayment:successes?Math.round(beamAmount/successes):0,paymentConversion:starts?successes/starts:null,displaySuccess:successes?displayed/successes:null},native:{payers:nativeCount,gmv:nativeAmount,currency:s.native_superchat_currency},adoption:{byPayers:(successes+nativeCount)?successes/(successes+nativeCount):null,byGmv:(beamAmount+nativeAmount)?beamAmount/(beamAmount+nativeAmount):null}}; }
}
